name: Deploy .NET MVC to MonsterASP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore DemoMVC/DemoMVC.csproj

      - name: Build project
        run: dotnet build DemoMVC/DemoMVC.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish DemoMVC/DemoMVC.csproj --configuration Release --output ./publish --no-build

      - name: Deploy App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./publish/
          server-dir: /wwwroot/
          security: loose